text_extensions:
- css
- erb
- haml
- htm
- html
- js
- less
- markdown
- md
- php
- rb
- sass
- txt
output_dir: output
index_filenames: [ 'index.html' ]
enable_output_diff: false
data_sources:
- type: filesystem_unified
  items_root: /
  layouts_root: /
base_url: "http://www.mao-yu.com"
author_name: "Mao Yu"
author_email: "contact@mao-yu.com"

